# Generated by Django 4.2.3 on 2024-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('car_type', models.CharField(choices=[('Electric', 'Electric'), ('Gas', 'Gas')], max_length=10)),
                ('battery_capacity', models.IntegerField(blank=True, null=True)),
                ('fuel_efficiency', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
